"""Serialized synthetic closure; excluded from native attendance and wages pending HR review."""

from datetime import timedelta

import frappe
from frappe.utils import get_datetime, get_system_timezone, now_datetime
from pypika.terms import ExistsCriterion

from reckon_hr_policy.policy import local_deadline
from reckon_hr_policy.utils.settings import settings


class PolicyCheckinMixin:
    def validate(self):
        # All ordinary inserts also acquire this lock, preventing a real OUT racing a synthetic one.
        frappe.db.get_value("Employee", self.employee, "name", for_update=True)
        previous = self.get_doc_before_save()
        if (
            self.get("rhp_auto_checkout_for") or (previous and previous.get("rhp_auto_checkout_for"))
        ) and not self.flags.rhp_auto_checkout:
            if self.is_new() or any(
                self.has_value_changed(f)
                for f in (
                    "rhp_auto_checkout_for",
                    "rhp_auto_checkout_reason",
                    "time",
                    "employee",
                    "log_type",
                    "skip_auto_attendance",
                )
            ):
                frappe.throw("Automatic checkout metadata may only be generated by the RHP scheduler")
        super().validate()

    def validate_distance_from_shift_location(self):
        if self.flags.rhp_auto_checkout:
            return  # Synthetic administrative record is not a physical geolocation claim.
        return super().validate_distance_from_shift_location()


def run():
    s = settings()
    if not s.enabled or not s.auto_checkout_enabled:
        return
    now = now_datetime()
    # Indexed keyset pagination covers old opens as well as new ones without repeated daily scans.
    cursor = None
    while True:
        c = frappe.qb.DocType("Employee Checkin")
        out = frappe.qb.DocType("Employee Checkin").as_("rhp_out")
        query = (
            frappe.qb.from_(c)
            .select(c.name, c.employee, c.time)
            .where(c.log_type == "IN")
            .where(c.time <= now - timedelta(hours=float(s.maximum_open_checkin_hours) - 2))
        )
        query = query.where(
            ExistsCriterion(
                frappe.qb.from_(out).select(out.name).where(out.rhp_auto_checkout_for == c.name)
            ).negate()
        )
        # Any later punch makes the original open ambiguous/completed. Never manufacture an old OUT across a later IN.
        query = query.where(
            ExistsCriterion(
                frappe.qb.from_(out)
                .select(out.name)
                .where((out.employee == c.employee) & (out.time > c.time))
            ).negate()
        )
        if cursor:
            query = query.where(c.name > cursor)
        candidates = query.orderby(c.name).limit(s.checkout_batch_size).run(as_dict=True)
        if not candidates:
            break
        for row in candidates:
            frappe.db.savepoint("rhp_checkout")
            try:
                close_one(row.name, s, now)
            except Exception:
                frappe.db.rollback(save_point="rhp_checkout")
                frappe.log_error(title=f"RHP automatic checkout: {row.name}", message=frappe.get_traceback())
        cursor = candidates[-1].name


def close_one(name, s=None, now=None):
    s = s or settings()
    now = now or now_datetime()
    source = frappe.get_doc("Employee Checkin", name)
    frappe.db.get_value("Employee", source.employee, "name", for_update=True)
    source.reload()
    if source.log_type != "IN" or frappe.db.exists("Employee Checkin", {"rhp_auto_checkout_for": name}):
        return None
    c = frappe.qb.DocType("Employee Checkin")
    following = (
        frappe.qb.from_(c)
        .select(c.name)
        .where((c.employee == source.employee) & (c.time >= source.time) & (c.name != name))
        .limit(1)
        .for_update()
        .run()
    )
    if following:
        return None
    due = local_deadline(
        get_datetime(source.time), float(s.maximum_open_checkin_hours), get_system_timezone()
    )
    if due > now:
        return None
    doc = frappe.get_doc(
        dict(
            doctype="Employee Checkin",
            employee=source.employee,
            log_type="OUT",
            time=due,
            skip_auto_attendance=1,
            rhp_auto_checkout_for=source.name,
            rhp_auto_checkout_reason=f"RHP maximum open checkin duration {s.maximum_open_checkin_hours} elapsed hours; administrative closure, excluded from attendance/payroll pending HR review.",
        )
    )
    doc.flags.rhp_auto_checkout = True
    doc.insert(ignore_permissions=True)
    return doc.name
