import hashlib
import json

import frappe


def freeze(doc, method=None):
    if not doc.rhp_calculation:
        return
    # Only trust calculation produced by the server in this submission lifecycle.
    if not getattr(doc, "_rhp_result", None):
        frappe.throw("Policy calculation was not generated by the payroll engine during submission")
    digest = hashlib.sha256(doc.rhp_calculation.encode()).hexdigest()
    if digest != doc.rhp_calculation_hash:
        frappe.throw("Policy calculation hash mismatch")
    if frappe.db.exists("Reckon HR Attendance Summary", {"salary_slip": doc.name}):
        frappe.throw("A policy snapshot already exists for this Salary Slip")
    summary = frappe.new_doc("Reckon HR Attendance Summary")
    data = json.loads(doc.rhp_calculation)
    for field in summary.meta.fields:
        if field.fieldname in data:
            summary.set(field.fieldname, data[field.fieldname])
    summary.salary_slip = doc.name
    summary.payroll_period = doc.current_payroll_period
    summary.calculation = doc.rhp_calculation
    summary.calculation_hash = digest
    summary.flags.rhp_freeze = True
    summary.insert(ignore_permissions=True)
